name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Fetch the entire Git history

      - name: Install PHP Dependencies with Composer
        uses: ramsey/composer-install@3.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1

      - name: Install jaq
        run: |
          curl -fsSL https://github.com/01mf02/jaq/releases/latest/download/jaq-$(uname -m)-unknown-linux-musl -o jaq && chmod +x jaq
          sudo mv jaq /usr/local/bin/jaq

      - name: Build JS and CSS
        run: |
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          include-hidden-files: true
          path: |
            .
            !node_modules
            !.git
            !.gitignore
            !.github
            !.vscode
            !.npmrc
            !prettier.config.cjs
            !vite.config.js

          retention-days: 1
          overwrite: true
